<?php

namespace Home\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubtaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtaskRepository extends EntityRepository
{
    public function getSubtaskByTask($task)
    {
     // получение Под задач по задаче с id
      $Query=$this->createQueryBuilder('S');
        If ($task)
        {
            $Query->Where('S.Task=:id');
            $Query->setParameter('id',$task);
            $result=$Query->getQuery();
            return $result->getResult();
        }
    }

    public function getTaskBySubtask($id_sub)
    {
        // получение Под задач по задаче с id
        $Query=$this->createQueryBuilder('S');
        If ($id_sub)
        {
            $Query->Where('S.id=:id');
            $Query->setParameter('id',$id_sub);
            $result=$Query->getQuery();
            return $result->getResult();
        }
    }
}
