task:
    path:     /
    defaults: { _controller: "HomeTaskBundle:Task:index" }

task_show:
    path:     /{id}/show
    defaults: { _controller: "HomeTaskBundle:Task:show" }

task_new:
    path:     /new
    defaults: { _controller: "HomeTaskBundle:Task:new" }

task_create:
    path:     /create
    defaults: { _controller: "HomeTaskBundle:Task:create" }
    requirements: { _method: post }

task_edit:
    path:     /{id}/edit
    defaults: { _controller: "HomeTaskBundle:Task:edit" }

task_update:
    path:     /{id}/update
    defaults: { _controller: "HomeTaskBundle:Task:update" }
    requirements: { _method: post|put }

task_delete:
    path:     /{id}/delete
    defaults: { _controller: "HomeTaskBundle:Task:delete" }
    requirements: { _method: post|delete }
task_category:
    path:     /{id_cat}/taskbycategory
    defaults: { _controller: "HomeTaskBundle:Task:TaskByCategory" }

hot_task:
    path: /hottask/
    defaults: { _controller: "HomeTaskBundle:Task:HotTask" }